lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # path to the private key
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # path to the public key
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        3600
    user_identity_field: email
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
